apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-analysis
  template:
    metadata:
      labels:
        app: banking-analysis
    spec:
      containers:
      - name: banking-app
        image: paulbrennan2021/banking_analysis:1.4
        ports:
        - containerPort: 8090
      
