apiVersion: v1
kind: Service
metadata:
  name: banking-analysis-entry-point
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8090
    targetPort: 8090
  selector:
    app: banking-analysis
